export { installPackage as addPackage, installPackage } from "installPackage"
export { installPackageNpm as addPackageNpm, installPackageNpm } from "installPackageNpm"
export { installPackagePnpm as addPackagePnpm, installPackagePnpm } from "installPackagePnpm"
export { installPackageYarn as addPackageYarn, installPackageYarn } from "installPackageYarn"
export { removePackage } from "removePackage"
export { removePackageNpm } from "removePackageNpm"
export { removePackagePnpm } from "removePackagePnpm"
export { removePackageYarn } from "removePackageYarn"
