name: Test nix install with nix installer

on: [push]

jobs:
  nix-cachix:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run "/usr/bin/bash --noprofile --norc -e -o pipefail {0}"

    steps:
      - uses: actions/checkout@v3
      - name: Create cache dir
        run: sudo mkdir -p /nixcache/store && sudo chown -R $USER /nixcache
        shell: bash
      - name: Load cache
        id: cache-nix-copy
        uses: actions/cache@v3
        with:
          path: /nixcache
          key: funkeyc4
      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Flag installed packages
        run: find /nix/store -mindepth 1 -maxdepth 1 > /nixcache/defaultstore.txt
        if: steps.cache-nix-copy.outputs.cache-hit == 'true'
        shell: bash
      - name: Restore cache
        run: sudo mv -n /nixcache/store/* /nix/store ; sudo $(which nix-store) --load-db < /nixcache/nix.db
        if: steps.cache-nix-copy.outputs.cache-hit == 'true'
        shell: bash
      - name: Setup postrun command to create cache
        uses: webiny/action-post-run@2.0.1
        id: prepare-cache
        with:
          run:
            bash -c "sudo rm -rf /nixcache/store ; mkdir -p /nixcache/store ; nix-store --dump-db > /nixcache/nix.db ;
            cat /nixcache/defaultstore.txt | xargs sudo rm -rf ; sudo rm /nixcache/defaultstore.txt ; sudo mv
            /nix/store/* /nixcache/store"

      - run: pnpm install
      - run: pnpm test
