name: Test nix install with nix installer

on: [push]

jobs:
  nix-cachix:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run "/bin/sh {0}"

    steps:
      - uses: actions/checkout@v3
      - name: Cache nix
        id: cache-nix
        uses: actions/cache@v3
        with:
          path: /nix
          key: nix-store
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - name: shelltest
        run: echo hi && echo $0 $1
        shell: /bin/sh {0}
        continue-on-error: true
      - name: shelltest 2
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "echo {0} "
        continue-on-error: true
      - name: shelltest 3
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "/bin/sh {0}"
        continue-on-error: true
      - name: shelltest 4
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "/bin/sh {0}.sh"
        continue-on-error: true
      - name: shelltest 5
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "ls $(basename {0})"
        continue-on-error: true
      - name: shelltest 6
        run: echo hi && echo $0 $1
        shell: nix-shell --run "echo {0}"
        continue-on-error: true
      - name: shelltest 7
        run: echo hi && echo $0 $1
        shell: nix-shell --run "/bin/sh {0}"
        continue-on-error: true
      - run: pnpm install
      - run: pnpm test
