name: Test with pnpm and node on ubuntu

on: [push]

jobs:
  nix-cachix:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run '/usr/bin/bash --noprofile --norc -e -o pipefail {0}'

    steps:
      - uses: actions/checkout@v3
      - name: Cache nix
        id: cache-nix
        uses: actions/cache@v3
        with:
          path: /nix
          key: nix-store
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - run: pnpm install
      - run: pnpm test
