name: Test pnpm with cached pnpm store and nodemodules

on: [push]

jobs:
  cache-pnpm-nodemodules:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run "/usr/bin/bash --noprofile --norc -e -o pipefail {0}"

    steps:
      - uses: actions/checkout@v3
      - name: Create cache dir
        run: sudo mkdir -p /nixcache/store && sudo chown -R $USER /nixcache
        shell: bash
      - name: Load cache
        id: cache-nix-copy
        uses: actions/cache@v3
        with:
          path: /nixcache
          key: funkeyz2
      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - name: Flag installed packages
        run: find /nix/store -mindepth 1 -maxdepth 1 > /nixcache/defaultstore.txt
        if: steps.cache-nix-copy.outputs.cache-hit != 'true'
        shell: bash
      - name: Restore cache
        run: |-
          sudo mv -n /nixcache/store/* /nix/store
          sudo $(which nix-store) --load-db < /nixcache/nix.db
        if: steps.cache-nix-copy.outputs.cache-hit == 'true'
        shell: bash
      - name: Setup postrun command to create cache
        uses: webiny/action-post-run@2.0.1
        id: prepare-cache
        with:
          run:
            bash -c "sudo rm -rf /nixcache/store ; mkdir -p /nixcache/store ; nix-store --dump-db > /nixcache/nix.db ;
            sudo rm /nixcache/defaultstore.txt ; sudo mv /nix/store/* /nixcache/store"
      - name: Find slow part bash
        run: |-
          time echo hi
          date
          time nix-shell --run "time echo ho"
          date
        shell: bash
      - name: Find slow part nixshell
        run: |-
          time echo hi
          date
          time nix-shell --run "time echo ho"
          date
      - name: Get pnpm step
        run: |-
          time echo hi
          time pnpm store path
          echo "::set-output name=PNPM_STORE::$(pnpm store path)"
          time echo hi
      - name: Pnpm cache
        id: cache-pnpm-store
        uses: actions/cache@v3
        with:
          path: |-
            ${{ steps.pnpm-store.outputs.PNPM_STORE }}
            node_modules
          key: funkeyz11

      - run: pnpm install
      - run: pnpm test
