name: Test nix install with nix installer

on: [push]

jobs:
  nix-cachix:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run "/usr/bin/bash --noprofile --norc -e -o pipefail {0}"

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - run: sudo stat /nix/store
        shell: bash
      - run: |-
          sudo rm -rf /nix/store && sudo mkdir -p /nix/store && sudo chown -R $USER /nix/store && sudo chmod a+rwx /nix/store
        shell: bash
      - name: Cache nix
        id: cache-nix-nix
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: funkey
      - run: sudo stat /nix/store
        shell: bash
      - run: |-
          sudo chown root:30000 /nix/store && chown root:0 /nix/store/* && sudo chmod 1775 /nix/store && sudo chmod -R a-w /nix/store
        shell: bash
      - run: sudo stat /nix/store
        shell: bash
      - run: pnpm install
      - run: pnpm test
      - run: ls /nix -a
      - run: stat /nix
      - run: stat /nix/store
