name: Test nix install with nix installer

on: [push]

jobs:
  nix-cachix:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run "/usr/bin/bash --noprofile --norc -e -o pipefail {0}"

    steps:
      - uses: actions/checkout@v3
      - run: sudo mkdir -p /nix
        shell: bash
      - run: sudo mkdir -p /nix/store &&  && sudo chown -R $USER /nix && sudo chmod -R a+rwx /nix
        shell: bash
      - name: Cache nix
        id: cache-nix-nix
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: storenixb
      - run: sudo stat /nix
        shell: bash
      - run: sudo chown -R root:30000 /nix
        shell: bash
      - run: sudo stat /nix
        shell: bash
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - run: pnpm install
      - run: pnpm test

      - run: ls /nix -a
      - run: stat /nix
      - run: stat /nix/store
