name: Test nix install with apt

on: [push]

jobs:
  nix-apt:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run "/usr/bin/bash --noprofile --norc -e -o pipefail {0}"

    steps:
      - uses: actions/checkout@v3
      - name: Cache nix store
        id: cache-nix
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: nix-store
      - uses: awalsh128/cache-apt-pkgs-action@v1.1.0
        with:
          packages: nix-setup-systemd
          version: 2
      - run: whoami
        shell: bash
      - name: shelltest
        run: echo hi && echo $0 $1
        shell: /bin/sh {0}
        continue-on-error: true
      - name: shelltest 2
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "echo {0} "
        continue-on-error: true
      - name: shelltest 3
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "/bin/sh {0}"
        continue-on-error: true
      - name: shelltest 4
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "/bin/sh {0}.sh"
        continue-on-error: true
      - name: shelltest 5
        run: echo hi && echo $0 $1
        shell: /bin/sh -c "ls $(basename {0})"
        continue-on-error: true
      - name: shelltest 6
        run: echo hi && echo $0 $1
        shell: nix-shell --run "echo {0}"
        continue-on-error: true
      - name: shelltest 7
        run: echo hi && echo $0 $1
        shell: nix-shell --run "/bin/sh {0}"
        continue-on-error: true
      - name: shelltest
        run: export
        shell: /bin/sh {0}
        continue-on-error: true
      - run: |-
          ls /nix/var/nix/profiles/per-user
          echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
          echo "max-jobs = auto" | sudo tee -a /etc/nix/nix.conf
          echo "build-users-group =" | sudo tee -a /etc/nix/nix.conf
          sudo chmod 0755 /etc/nix
          echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
          echo "/nix/var/nix/profiles/per-user/$USER/profile/bin" >> "$GITHUB_PATH"
        shell: /bin/sh {0}
        continue-on-error: true
      - run: stat /etc/nix/nix.conf
        shell: bash
      - run: cat /etc/nix/nix.conf
        shell: bash
      - run: sudo nix-channel --add https://nixos.org/channels/nixos-22.05 nixpkgs
        shell: bash
      - run: sudo nix-channel --update
        shell: bash

      - run: pnpm install
      - run: pnpm test
