name: Test nix install with nix installer

on: [push]

jobs:
  nix-cachix:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run "/usr/bin/bash --noprofile --norc -e -o pipefail {0}"

    steps:
      - uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - run: sudo nix-store --verify --repair --check-contents
        shell: bash
      - name: Move files away
        run: sudo mkdir -p /storetmp && sudo mv /nix/store/* /storetmp
        shell: bash
      - run: sudo stat /nix/store && sudo ls /nix/store | wc
        shell: bash
      - run: |-
          sudo rm -rf /nix/store && sudo mkdir -p /nix/store && sudo chown -R $USER /nix/store && sudo chmod a+rwx /nix/store
        shell: bash
      - name: Load cache
        id: cache-nix-nix
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: funkeyb
      - run: stat  /nix/store/069i7sasmcvwxwz3dx2g55xmnl38zjb1-openssl-1.1.1q-dev || true
        shell: bash
      - run: sudo stat /nix/store  && sudo ls /nix/store | wc
        shell: bash
      - name: Move files back
        run: sudo mkdir -p /nix/store && sudo mv -n /storetmp/* /nix/store
        shell: bash
      - run: sudo stat /nix/store  && sudo ls /nix/store | wc
        shell: bash
      - run: |-
          sudo chown -R root:0 /nix/store && sudo chown root:30000 /nix/store && sudo chmod 1775 /nix/store && sudo chmod -R a-w /nix/store
        shell: bash
      - run: sudo stat /nix/store && sudo ls /nix/store | wc
        shell: bash
      - run: stat  /nix/store/069i7sasmcvwxwz3dx2g55xmnl38zjb1-openssl-1.1.1q-dev || true
        shell: bash
      - run: pnpm install
      - run: stat  /nix/store/069i7sasmcvwxwz3dx2g55xmnl38zjb1-openssl-1.1.1q-dev || true
        shell: bash
      - run: pnpm test
      - run: ls /nix -a
      - run: stat /nix
      - run: stat  /nix/store/069i7sasmcvwxwz3dx2g55xmnl38zjb1-openssl-1.1.1q-dev || true
        shell: bash
