name: Test nix install with nix installer

on: [push]

jobs:
  nix-cachix:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run '/usr/bin/bash {0}.sh'

    steps:
      - uses: actions/checkout@v3
      - name: Cache nix
        id: cache-nix
        uses: actions/cache@v3
        with:
          path: /nix
          key: nix-store
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - name: shelltest
        run: echo hi
        shell: /usr/bin/bash -c 'ls $(dirname {0} )'
      - run: pnpm install
      - run: pnpm test
