name: Test nix install with apt

on: [push]

jobs:
  nix-apt:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix-shell --run '/usr/bin/bash --noprofile --norc -e -o pipefail {0}'

    steps:
      - uses: actions/checkout@v3
      - name: Cache nix
        id: cache-nix
        uses: actions/cache@v3
        with:
          path: /nix
          key: nix-store
      - uses: awalsh128/cache-apt-pkgs-action@v1.1.0
        with:
          packages: nix-setup-systemd
          version: 1
      - run: nix-channel --add https://nixos.org/channels/nixos-22.05 nixpkgs && nix-channel --update
        shell: bash

      - run: pnpm install
      - run: pnpm test
